services:
  - type: web
    name: nota-backend
    runtime: python
    plan: free
    branch: main
    autoDeploy: true
    healthCheckPath: /health

    # Fuerza Python 3.12.6 en Render
    pythonVersion: 3.12.6

    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir -r requirements.txt
      chmod +x start.sh
      mkdir -p backend/data
      if [ -n "$GCS_MEDICAL_FTS_URL" ]; then
        echo "Descargando medical_fts.sqlite..."
        curl -fsSL "$GCS_MEDICAL_FTS_URL" -o backend/data/medical_fts.sqlite || true
      fi
      if [ -n "$GCS_OUTPUT_DB_URL" ]; then
        echo "Descargando output.db..."
        curl -fsSL "$GCS_OUTPUT_DB_URL" -o backend/data/output.db || true
      fi

    # Usamos tu script start.sh
    startCommand: ./start.sh

    envVars:
      # Entorno app
      - key: ENV
        value: production
      - key: ENABLE_DOCS
        value: "false"
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: TRUSTED_HOSTS
        value: "*.onrender.com,localhost,127.0.0.1"
      - key: FORCE_HTTPS
        value: "false"

      # Rutas internas de datos (efímeras)
      - key: DATA_DIR
        value: /opt/render/project/src/backend/data
      - key: SQLITE_DB
        value: /opt/render/project/src/backend/data/medical.db
      - key: IOS_FTS_DB
        value: /opt/render/project/src/backend/data/medical_fts.sqlite
      - key: OUTPUT_DB
        value: /opt/render/project/src/backend/data/output.db

      # Preferencias de ranking
      - key: PREFERRED_DOMAINS
        value: "minsal.cl,intramed.net,medlineplus.gov,mayoclinic.org"

      # Descarga opcional de bases (configúralas en el Dashboard)
      - key: GCS_MEDICAL_FTS_URL
        sync: false
      - key: GCS_OUTPUT_DB_URL
        sync: false

      # Buscador (si usas legacy search client)
      - key: SEARCH_ENGINE
        value: GOOGLE
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_CX
        sync: false
      - key: BING_KEY
        sync: false
      - key: BING_ENDPOINT
        value: https://api.bing.microsoft.com/v7.0/search
      - key: BING_MKT
        value: es-CL

      # LLM (si apuntas a un endpoint público/externo)
      - key: LLM_BASE_URL
        sync: false
      - key: LLM_MODEL
        sync: false
      - key: LLM_API_KEY
        sync: false

      # (Opcional) proteger /chat
      - key: SERVER_API_KEY
        sync: false