services:
  - type: web
    name: nota-backend
    runtime: python           # (nuevo esquema)
    plan: free
    branch: main
    autoDeploy: true
    healthCheckPath: /health

    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir -r backend/requirements.txt
      mkdir -p backend/data
      if [ -n "$GCS_MEDICAL_FTS_URL" ]; then
        curl -fsSL "$GCS_MEDICAL_FTS_URL" -o backend/data/medical_fts.sqlite || true
      fi
      if [ -n "$GCS_OUTPUT_DB_URL" ]; then
        curl -fsSL "$GCS_OUTPUT_DB_URL" -o backend/data/output.db || true
      fi

    startCommand: >
      uvicorn backend.app:app
      --host 0.0.0.0 --port $PORT
      --proxy-headers --forwarded-allow-ips="*"
      --timeout-keep-alive 65

    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6

      - key: ENV
        value: production
      - key: ENABLE_DOCS
        value: "false"

      # CORS
      - key: ALLOWED_ORIGINS
        value: "*"

      # MUY IMPORTANTE: hosts de confianza (comodín para Render)
      - key: TRUSTED_HOSTS
        value: "*.onrender.com,localhost,127.0.0.1"

      # Rutas de datos (efímeras, válidas en Render)
      - key: DATA_DIR
        value: /opt/render/project/src/backend/data
      - key: IOS_FTS_DB
        value: /opt/render/project/src/backend/data/medical_fts.sqlite
      - key: OUTPUT_DB
        value: /opt/render/project/src/backend/data/output.db

      # Motor de búsqueda y ranking
      - key: SEARCH_ENGINE
        value: GOOGLE
      - key: PREFERRED_DOMAINS
        value: "minsal.cl,intramed.net,medlineplus.gov,mayoclinic.org"

      # (Opcional) URLs para bajar las SQLite
      - key: GCS_MEDICAL_FTS_URL
        sync: false
      - key: GCS_OUTPUT_DB_URL
        sync: false

      # Claves — pon el valor en el dashboard
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_CX
        sync: false
      - key: BING_KEY
        sync: false
      - key: BING_ENDPOINT
        value: https://api.bing.microsoft.com/v7.0/search
      - key: BING_MKT
        value: es-CL

      # (Opcional) proteger /chat con API key de servidor
      - key: SERVER_API_KEY
        sync: false