services:
  - type: web
    name: nota-backend
    env: python
    plan: free
    branch: main
    autoDeploy: true

    healthCheckPath: /health

    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir -r backend/requirements.txt

      # ↓ Descarga opcional de DBs locales (válido en plan free dentro del build)
      mkdir -p backend/data
      if [ -n "$GCS_MEDICAL_FTS_URL" ]; then
        echo "Descargando medical_fts.sqlite..."
        curl -fsSL "$GCS_MEDICAL_FTS_URL" -o backend/data/medical_fts.sqlite || echo "No se pudo descargar medical_fts.sqlite"
      fi
      if [ -n "$GCS_OUTPUT_DB_URL" ]; then
        echo "Descargando output.db..."
        curl -fsSL "$GCS_OUTPUT_DB_URL" -o backend/data/output.db || echo "No se pudo descargar output.db"
      fi

    startCommand: >
      uvicorn backend.app:app
      --host 0.0.0.0 --port $PORT
      --proxy-headers --forwarded-allow-ips="*"
      --timeout-keep-alive 65

    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6

      # App config
      - key: ENV
        value: production
      - key: ENABLE_DOCS
        value: "false"
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: TRUSTED_HOSTS
        value: "nota-backend.onrender.com,.onrender.com"
      # - key: WEB_CONCURRENCY
      #   value: "1"

      # Rutas de datos (dentro de la imagen)
      - key: DATA_DIR
        value: /opt/render/project/src/backend/data
      - key: IOS_FTS_DB
        value: /opt/render/project/src/backend/data/medical_fts.sqlite
      - key: OUTPUT_DB
        value: /opt/render/project/src/backend/data/output.db

      # Búsqueda
      - key: SEARCH_ENGINE
        value: GOOGLE
      - key: PREFERRED_DOMAINS
        value: "minsal.cl,intramed.net,medlineplus.gov,mayoclinic.org"

      # URLs (se recomiendan firmadas/públicas solo lectura)
      - key: GCS_MEDICAL_FTS_URL
        sync: false
      - key: GCS_OUTPUT_DB_URL
        sync: false

      # Claves (poner valores en el dashboard, no en el YAML)
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_CX
        sync: false
      - key: BING_KEY
        sync: false
      - key: BING_ENDPOINT
        value: https://api.bing.microsoft.com/v7.0/search
      - key: BING_MKT
        value: es-CL

      # API Key del backend (opcional, para /chat)
      - key: SERVER_API_KEY
        sync: false