services:
  - type: web
    name: nota-backend
    env: python
    plan: free
    branch: main
    autoDeploy: true

    healthCheckPath: /health

    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir -r backend/requirements.txt

    startCommand: >
      uvicorn backend.app:app
      --host 0.0.0.0 --port $PORT
      --proxy-headers --forwarded-allow-ips="*"
      --timeout-keep-alive 65

    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6

      # Datos locales (persistentes en el disco)
      - key: DATA_DIR
        value: /opt/render/project/src/backend/data
      - key: IOS_FTS_DB
        value: /opt/render/project/src/backend/data/medical_fts.sqlite
      - key: OUTPUT_DB
        value: /opt/render/project/src/backend/data/output.db

      # CORS (ajústalo en prod)
      - key: ALLOWED_ORIGINS
        value: "*"

      # Motor de búsqueda
      - key: SEARCH_ENGINE
        value: GOOGLE

      # Opcional: prioriza dominios “buenos”
      - key: PREFERRED_DOMAINS
        value: "minsal.cl,intramed.net,medlineplus.gov,mayoclinic.org"

      # === Claves (configúralas en el dashboard) ===
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_CX
        sync: false
      - key: BING_KEY
        sync: false
      - key: BING_ENDPOINT
        value: https://api.bing.microsoft.com/v7.0/search
      - key: BING_MKT
        value: es-CL

    disk:
      name: nota-data
      mountPath: /opt/render/project/src/backend/data
      sizeGB: 1