services:
  - type: web
    name: nota-backend
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: DATA_DIR
        value: /app/backend/data
      - key: SEARCH_ENGINE
        value: google
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_CX
        sync: false
      - key: BING_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: IOS_FTS_DB
        value: /app/backend/data/medical_fts.sqlite
      - key: OUTPUT_DB
        value: /app/backend/data/output.db
      - key: PREFERRED_DOMAINS
        value: minsal.cl,intramed.net,who.int,cdc.gov
      - key: IOS_FTS_URL
        sync: false
      - key: OUTPUT_DB_URL
        sync: false