services:
  - type: web
    name: nota-backend
    runtime: python
    branch: main
    autoDeploy: true
    healthCheckPath: /health

    buildCommand: |
      pip install -U pip
      pip install -r backend/requirements.txt

    startCommand: >
      uvicorn backend.app:app
      --host 0.0.0.0 --port $PORT
      --proxy-headers --forwarded-allow-ips="*"

    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
      - key: DATA_DIR
        value: /opt/render/project/src/backend/data
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: SEARCH_ENGINE
        value: GOOGLE

      # ==== Claves (ponlas en el dashboard de Render) ====
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_CX
        sync: false
      - key: BING_KEY
        sync: false
      - key: BING_ENDPOINT
        value: https://api.bing.microsoft.com/v7.0/search
      - key: BING_MKT
        value: es-CL

    disk:
      name: nota-data
      mountPath: /opt/render/project/src/backend/data
      sizeGB: 1